/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.np.admin.forme.korisnik;

import rs.np.controller.ControllerAdministrator;
import domenskiObjekti.Korisnik;
import domenskiObjekti.TipKorisnika;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Viktor
 */
public class CRUDKorisnikaForma extends javax.swing.JDialog {

    
    private Korisnik trenutniKorisnik=null;
    /**
     * Creates new form DodajKorisnikaForma
     */
    public CRUDKorisnikaForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaslov = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtBrojTelefona = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnDodaj = new javax.swing.JButton();
        btnVidi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodavanje korisnika");

        lblNaslov.setText("Novi korisnik");

        jLabel2.setText("Ime: ");

        jLabel3.setText("Prezime: ");

        jLabel4.setText("Broj Telefona:");

        jLabel5.setText("Username: ");

        jLabel6.setText("Password:");

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnVidi.setText("Vidi");
        btnVidi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVidiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNaslov)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtBrojTelefona, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(80, 80, 80)
                                        .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                            .addComponent(txtPassword))))
                                .addGap(18, 18, 18)
                                .addComponent(btnVidi))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNaslov)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBrojTelefona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVidi))
                .addGap(33, 33, 33)
                .addComponent(btnDodaj)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVidiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVidiActionPerformed
        ButtonModel bModel = btnVidi.getModel();
        bModel.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                if (bModel.isPressed()) {
                    txtPassword.setEchoChar((char) 0);
                } else if (!bModel.isPressed()) {
                    txtPassword.setEchoChar('*');
                }
            }
        });

    }//GEN-LAST:event_btnVidiActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        if (!validirajPolja()) {
            JOptionPane.showMessageDialog(this, "Losi podaci");
            return;
        }

        String ime = txtIme.getText();
        String prezime = txtPrezime.getText();
        String brojTelefona = txtBrojTelefona.getText();
        String username = txtUsername.getText();
        String password = String.valueOf(txtPassword.getPassword());
        
        //SLUCAJ GDE SE FORMA KORISTI ZA DODAVANJE KORISNIKA
        if (btnDodaj.getText().equals("Dodaj")) {
            int znak=0;
            try {
                znak = ControllerAdministrator.getInstance().dodajKorisnika(ime, prezime, brojTelefona, username, password);
            } catch (SQLException ex) {
                Logger.getLogger(CRUDKorisnikaForma.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (znak == 1) {
                txtIme.setText("");
                txtBrojTelefona.setText("");
                txtPassword.setText("");
                txtPrezime.setText("");
                txtUsername.setText("");
                JOptionPane.showMessageDialog(this, "Korisnik " + ime + " " + prezime + " uspesno dodat");
            } else {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti korisnika.\n (Proverite da li vec postoji korisnik sa istim korisnickim imenom)","Greska",JOptionPane.WARNING_MESSAGE);      
            }
        }
        //SLUCAJ GDE SE FORMA KORISTI ZA IZMENU KORISNIKA
        else{
            if(trenutniKorisnik==null){
                JOptionPane.showMessageDialog(this, "Tekuci korisnik nije inicijalizovan");
                return;
            }
            int znak=0;
            Korisnik k=new Korisnik(trenutniKorisnik.getKorisnikId(), username, password, ime, prezime, brojTelefona, TipKorisnika.KORISNIK,false);
            try {
                znak=ControllerAdministrator.getInstance().izmeniKorisnika(k);
            } catch (Exception ex) {
                Logger.getLogger(CRUDKorisnikaForma.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(znak>=1){
                JOptionPane.showMessageDialog(this, "Korisnik " + ime + " " + prezime + " uspesno izmenjen");
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti korisnika","Greska",JOptionPane.WARNING_MESSAGE);
                this.dispose();
            }
        }
        
        
        
    }//GEN-LAST:event_btnDodajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDKorisnikaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDKorisnikaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDKorisnikaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDKorisnikaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnVidi;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JTextField txtBrojTelefona;
    private javax.swing.JTextField txtIme;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private boolean validirajPolja() {
        if (txtIme.getText().length() < 2) {
            return false;
        }
        if (txtPrezime.getText().length() < 2) {
            return false;
        }
        if (txtBrojTelefona.getText().length() < 6) {
            return false;
        }
        if (txtUsername.getText().length() < 2) {
            return false;
        }
        if (String.valueOf(txtPassword.getPassword()).length() < 3) {
            return false;
        }
        return true;
    }

    public void izmenaKorisnika(Korisnik k) {

        lblNaslov.setText("Izmena korisnika");
        btnDodaj.setText("Izmeni");
        txtIme.setText(k.getIme());
        txtBrojTelefona.setText(k.getTelefon());
        txtPrezime.setText(k.getPrezime());
        txtUsername.setText(k.getUsername());
        txtPassword.setText(k.getPassword());
        this.setTitle("Izmena korisnika");
        this.trenutniKorisnik=k;
        
    }

}
